---
apiVersion: v1
kind: Secret
metadata:
  name: truenas-secret
  namespace: hpe-storage
stringData:
  serviceName: truenas-csp-svc
  servicePort: "8080"
  username: hpe-csi (username is a no-op)
  password: API key or root password of TrueNAS/FreeNAS appliance
  backend: Management IP address of TrueNAS/FreeNAS appliance
