apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: hpereplicationdeviceinfos.storage.hpe.com
spec:
  group: storage.hpe.com
  names:
    kind: HPEReplicationDeviceInfo
    plural: hpereplicationdeviceinfos
    shortNames:
      - hperdi

  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        hpeReplicationDeviceInfos:
          description: List of HPE Replicated Arrays configured for 3PAR/Primera arrays.
          items:
            properties:
              targets:
                description: Target Array Details
                type: array
                items:
                  properties:
                    targetName:
                      description: Target Name of the array
                      type: string
                    targetCpg:
                      description: Target CPG of the array
                      type: string
                    targetSnapCpg:
                      description: Target Snap CPG of the array
                      type: string
                    targetSecret:
                      description: Secret of the replicated array
                      type: string
                    targetMode:
                      description: Replication Mode
                      type: string
                    targetSecretNamespace:
                      description: Namespace of secret
                      type: string
                  required:
                    - targetName
                    - targetCpg
                    - targetSecret
                    - targetSecretNamespace
          type: array
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
