apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: hpevolumeinfos.storage.hpe.com
spec:
  group: storage.hpe.com
  names:
    kind: HPEVolumeInfo
    plural: hpevolumeinfos
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        hpeVolumes:
          description: List of HPE volumes configured for 3PAR/Primera arrays.
          items:
            properties:
              uuid:
                description: The UUID of the volume.
                type: string
              record:
                description: Metadata for the volume.
                type: map[string]string
          type: array
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
