apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: hpesnapshotgroupinfos.storage.hpe.com
spec:
  group: storage.hpe.com
  names:
    kind: HPESnapshotGroupInfo
    plural: hpesnapshotgroupinfos
    shortNames: 
      - hpesgi
  scope: Cluster
  version: v1
  validation:
    openAPIV3Schema:
      properties:
        hpeSnapshotGroupInfos:
          description: List of HPE snapshot groups created for 3PAR/Primera arrays.
          type: array
          items:
            properties:
              uuid:
                description: The UUID of the node.
                type: string
          
              record:
                description: Metadata for the volume group
                type: map[string]string

              snapshotVolumes:
                description: Snapshot volumes that are part of this snapshot group
                type: array
                items:
                  properties:
                    srcVolumeId:
                      description: ID of the volume that is the source of this snapshot volume 
                      type: string

                    srcVolumeName:
                      description: Name of the volume that is the source of this snapshot volume
                      type: string

                    snapshotId:
                      description: Snapshot volume Id
                      type: string

                    snapshotName:
                      description: Snapshot volume name
                      type: string

status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
