---
#############################################
############  HPE Node Info CRD  ############
#############################################
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata: 
  creationTimestamp: null
  name: hpenodeinfos.storage.hpe.com
spec: 
  group: storage.hpe.com
  names: 
    kind: HPENodeInfo
    plural: hpenodeinfos
  scope: Cluster
  versions: 
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema: 
        openAPIV3Schema: 
          properties: 
            apiVersion: 
              description: "APIVersion defines the versioned schema of this representation of an object."
              type: string
            kind: 
              description: "Kind is a string value representing the REST resource this object represents"
              type: string
            spec: 
              description: "spec defines the desired characteristics of a HPE nodeinfo requested by a user."
              properties: 
                chapPassword: 
                  description: "The CHAP Password"
                  type: string
                chapUser: 
                  description: "The CHAP User Name"
                  type: string
                iqns: 
                  description: "List of IQNs configured on the node."
                  items: 
                    type: string
                  type: array
                networks: 
                  description: "List of networks configured on the node."
                  items: 
                    type: string
                  type: array
                uuid: 
                  description: "The UUID of the node."
                  type: string
                wwpns: 
                  description: "List of WWPNs configured on the node."
                  items: 
                    type: string
                  type: array
              required: 
                - uuid
                - networks
              type: object
          required: 
            - spec
          type: object
status: 
  acceptedNames: 
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []