apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: hpevolumegroupinfos.storage.hpe.com
spec:
  group: storage.hpe.com
  names:
    kind: HPEVolumeGroupInfo
    plural: hpevolumegroupinfos
    shortNames: 
      - hpevgi
  scope: Cluster
  version: v1
  validation:
    openAPIV3Schema:
      properties:
        hpeVolumeGroupInfos:
          description: List of HPE volume groups configured for 3PAR/Primera arrays.
          type: array
          items:
            properties:
              uuid:
                description: The UUID of the node.
                type: string
          
              record:
                description: Metadata for the volume group
                type: map[string]string

              snapshotGroups:
                description: Snapshot groups that are linked to this volume group
                type: array
                items:
                  properties:
                    id:
                      description: ID of the snapshot group
                      type: string

                    name:
                      description: Name of the snapshot group
                      type: string

              volumes:
                description: Volumes that are members in this volume group
                type: array
                items:
                  properties:
                    volumeId:
                      description: ID of the member volume 
                      type: string

                    volumeName:
                      description: Name of the member volume
                      type: string



status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
