---
kind: Service
apiVersion: v1
metadata:
  name: truenas-csp-svc
  namespace: kube-system
  labels:
    app: truenas-csp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: truenas-csp

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: truenas-csp
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: truenas-csp
  replicas: 1
  template:
    metadata:
      labels:
        app: truenas-csp
    spec:
      priorityClassName: system-cluster-critical
      containers:
        - name: truenas-csp
          image: hpestorage/truenas-csp:edge
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
