---
apiVersion: v1
kind: Secret
metadata:
  name: truenas-secret
  namespace: kube-system 
stringData:
  serviceName: truenas-csp-svc
  servicePort: "8080"
  username: hpe-csi
  password: TrueNAS CORE API key
  backend: TrueNAS CORE management IP address
