annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://scod.hpedev.io/csi_driver
  artifacthub.io/prerelease: "false"
apiVersion: v1
appVersion: 2.0.0
description: A Helm chart for installing the HPE CSI Driver for Kubernetes
home: https://hpe.com/storage/containers
icon: https://raw.githubusercontent.com/hpe-storage/co-deployments/master/docs/assets/hpedev.png
keywords:
- HPE
- Storage
- CSI
maintainers:
- email: hpe-containers-dev@hpe.com
  name: raunakkumar
name: hpe-csi-driver
sources:
- https://github.com/hpe-storage/co-deployments
- https://github.com/hpe-storage/csi-driver
version: 2.0.0
