# Default values for hpe-csi-driver Helm chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Control CSP Service and Deployments for HPE storage products
disable:
  nimble: false
  primera: false
  alletra6000: false
  alletra9000: false

# For controlling automatic iscsi/multipath package installation
disableNodeConformance: false

# imagePullPolicy applied for all hpe-csi-driver images
imagePullPolicy: "IfNotPresent"

# Cluster wide values for CHAP authentication
iscsi:
  chapUser: ""
  chapPassword: ""

# Log level for all hpe-csi-driver components
logLevel: "info"

# Registry prefix for hpe-csi-driver images
registry: "quay.io"

# Kubelet root directory path
kubeletRootDir: "/var/lib/kubelet/"

# NodeGetVolumestats will be called by default, set true to disable the call 
disableNodeGetVolumeStats: false

# CSP client timeout for HPE Alletra 9000, Primera and 3PAR (60-360 seconds)
cspClientTimeout: 60
