---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hpe-linux-config
  namespace: {{ .Release.Namespace }}
data:
{{ if and .Values.iscsi.chapUser .Values.iscsi.chapPassword }}
  CHAP_USER: {{ .Values.iscsi.chapUser  | quote }}
  CHAP_PASSWORD: {{ .Values.iscsi.chapPassword  | quote }}
{{- end }}
  config.json: |-
{{ (.Files.Get "files/config.json") | indent 4 }}