---
apiVersion: v1
kind: Secret
metadata:
  name: truenas-secret
  namespace: hpe-storage
stringData:
  serviceName: truenas-csp-svc
  servicePort: "8080"
  username: hpe-csi
  password: TrueNAS CORE API key # For FreeNAS 11.3, set to "root:<root_password>"
  backend: TrueNAS CORE management IP address
