---
apiVersion: v1
kind: Secret
metadata:
  name: truenas-secret
  namespace: hpe-storage
stringData:
  serviceName: truenas-csp-svc
  servicePort: "8080"
  username: hpe-csi # "root" for FreeNAS 11.3
  password: TrueNAS CORE API key # root password for FreeNAS 11.3
  backend: TrueNAS CORE management IP address
